package com.example.jobfinder.ui.theme

import androidx.compose.ui.graphics.Color

// ===== JobFinder (original) colors =====

val md_theme_light_primary = Color(0xFF6750A4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFEADDFF)
val md_theme_light_onPrimaryContainer = Color(0xFF21005D)
val md_theme_light_secondary = Color(0xFF625B71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE8DEF8)
val md_theme_light_onSecondaryContainer = Color(0xFF1D192B)
val md_theme_light_tertiary = Color(0xFF7D5260)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD8E4)
val md_theme_light_onTertiaryContainer = Color(0xFF31111D)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_background = Color(0xFFFFFBFE)
val md_theme_light_onBackground = Color(0xFF1C1B1F)
val md_theme_light_surface = Color(0xFFFFFBFE)
val md_theme_light_onSurface = Color(0xFF1C1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_inverseSurface = Color(0xFF313033)
val md_theme_light_inverseOnSurface = Color(0xFFF4EFF4)
val md_theme_light_inversePrimary = Color(0xFFD0BCFF)
val md_theme_light_surfaceTint = Color(0xFF6750A4)
val md_theme_light_outlineVariant = Color(0xFFCAC4D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFD0BCFF)
val md_theme_dark_onPrimary = Color(0xFF381E72)
val md_theme_dark_primaryContainer = Color(0xFF4F378B)
val md_theme_dark_onPrimaryContainer = Color(0xFFEADDFF)
val md_theme_dark_secondary = Color(0xFFCCC2DC)
val md_theme_dark_onSecondary = Color(0xFF332D41)
val md_theme_dark_secondaryContainer = Color(0xFF4A4458)
val md_theme_dark_onSecondaryContainer = Color(0xFFE8DEF8)
val md_theme_dark_tertiary = Color(0xFFEFB8C8)
val md_theme_dark_onTertiary = Color(0xFF492532)
val md_theme_dark_tertiaryContainer = Color(0xFF633B48)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD8E4)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_background = Color(0xFF1C1B1F)
val md_theme_dark_onBackground = Color(0xFFE6E1E5)
val md_theme_dark_surface = Color(0xFF1C1B1F)
val md_theme_dark_onSurface = Color(0xFFE6E1E5)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_inverseSurface = Color(0xFFE6E1E5)
val md_theme_dark_inverseOnSurface = Color(0xFF313033)
val md_theme_dark_inversePrimary = Color(0xFF6750A4)
val md_theme_dark_surfaceTint = Color(0xFFD0BCFF)
val md_theme_dark_outlineVariant = Color(0xFF49454F)
val md_theme_dark_scrim = Color(0xFF000000)






// ===== Search colors =====

val starIconGradient = listOf(
    Color(0xFFFFAB61),
    Color(0xFF631C13)
)

val gradientColors = listOf(
    Color.Cyan, Color(0xFF0076F5)
)

val blackWhiteGradient = listOf(
    Color.White, Color.Black
)

val primaryLight = Color(0xFF00696E)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF9CF0F5)
val onPrimaryContainerLight = Color(0xFF002021)
val secondaryLight = Color(0xFF4A6364)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCCE8E9)
val onSecondaryContainerLight = Color(0xFF041F21)
val tertiaryLight = Color(0xFF4E5F7D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFD6E3FF)
val onTertiaryContainerLight = Color(0xFF081C36)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF4FAFA)
val onBackgroundLight = Color(0xFF161D1D)
val surfaceLight = Color(0xFFF4FAFA)
val onSurfaceLight = Color(0xFF161D1D)
val surfaceVariantLight = Color(0xFFDAE4E5)
val onSurfaceVariantLight = Color(0xFF3F4949)
val outlineLight = Color(0xFF6F7979)
val outlineVariantLight = Color(0xFFBEC8C9)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3232)
val inverseOnSurfaceLight = Color(0xFFECF2F2)
val inversePrimaryLight = Color(0xFF80D4D9)
val surfaceDimLight = Color(0xFFD5DBDB)
val surfaceBrightLight = Color(0xFFF4FAFA)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F5)
val surfaceContainerLight = Color(0xFFE9EFEF)
val surfaceContainerHighLight = Color(0xFFF4FAFA)
val surfaceContainerHighestLight = Color(0xFFDDE4E4)

val primaryLightMediumContrast = Color(0xFF004B4E)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF238085)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF2E4748)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF60797B)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF32435F)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF647594)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF4FAFA)
val onBackgroundLightMediumContrast = Color(0xFF161D1D)
val surfaceLightMediumContrast = Color(0xFFF4FAFA)
val onSurfaceLightMediumContrast = Color(0xFF161D1D)
val surfaceVariantLightMediumContrast = Color(0xFFDAE4E5)
val onSurfaceVariantLightMediumContrast = Color(0xFF3B4545)
val outlineLightMediumContrast = Color(0xFF576161)
val outlineVariantLightMediumContrast = Color(0xFF737D7D)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2B3232)
val inverseOnSurfaceLightMediumContrast = Color(0xFFECF2F2)
val inversePrimaryLightMediumContrast = Color(0xFF80D4D9)
val surfaceDimLightMediumContrast = Color(0xFFD5DBDB)
val surfaceBrightLightMediumContrast = Color(0xFFF4FAFA)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFEFF5F5)
val surfaceContainerLightMediumContrast = Color(0xFFE9EFEF)
val surfaceContainerHighLightMediumContrast = Color(0xFFEFF3F3)
val surfaceContainerHighestLightMediumContrast = Color(0xFFDDE4E4)

val primaryLightHighContrast = Color(0xFF002729)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF004B4E)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF0C2627)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF2E4748)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF10223D)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF32435F)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF4E0002)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF8C0009)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFF4FAFA)
val onBackgroundLightHighContrast = Color(0xFF161D1D)
val surfaceLightHighContrast = Color(0xFFF4FAFA)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFDAE4E5)
val onSurfaceVariantLightHighContrast = Color(0xFF1C2626)
val outlineLightHighContrast = Color(0xFF3B4545)
val outlineVariantLightHighContrast = Color(0xFF3B4545)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF2B3232)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFA6FAFF)
val surfaceDimLightHighContrast = Color(0xFFD5DBDB)
val surfaceBrightLightHighContrast = Color(0xFFF4FAFA)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFEFF5F5)
val surfaceContainerLightHighContrast = Color(0xFFE9EFEF)
val surfaceContainerHighLightHighContrast = Color(0xFFE3E9E9)
val surfaceContainerHighestLightHighContrast = Color(0xFFDDE4E4)

val primaryDark = Color(0xFF80D4D9)
val onPrimaryDark = Color(0xFF003739)
val primaryContainerDark = Color(0xFF004F53)
val onPrimaryContainerDark = Color(0xFF9CF0F5)
val secondaryDark = Color(0xFFB1CCCD)
val onSecondaryDark = Color(0xFF1B3436)
val secondaryContainerDark = Color(0xFF324B4C)
val onSecondaryContainerDark = Color(0xFFCCE8E9)
val tertiaryDark = Color(0xFFB5C7E9)
val onTertiaryDark = Color(0xFF1F314C)
val tertiaryContainerDark = Color(0xFF364764)
val onTertiaryContainerDark = Color(0xFFD6E3FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF0E1415)
val onBackgroundDark = Color(0xFFDDE4E4)
val surfaceDark = Color(0xFF0E1415)
val onSurfaceDark = Color(0xFFDDE4E4)
val surfaceVariantDark = Color(0xFF3F4949)
val onSurfaceVariantDark = Color(0xFFBEC8C9)
val outlineDark = Color(0xFF899393)
val outlineVariantDark = Color(0xFF3F4949)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDDE4E4)
val inverseOnSurfaceDark = Color(0xFF2B3232)
val inversePrimaryDark = Color(0xFF00696E)
val surfaceDimDark = Color(0xFF0E1415)
val surfaceBrightDark = Color(0xFF343A3B)
val surfaceContainerLowestDark = Color(0xFF090F10)
val surfaceContainerLowDark = Color(0xFF161D1D)
val surfaceContainerDark = Color(0xFF1A2121)
val surfaceContainerHighDark = Color(0xFF252B2B)
val surfaceContainerHighestDark = Color(0xFF303636)

val primaryDarkMediumContrast = Color(0xFF84D8DD)
val onPrimaryDarkMediumContrast = Color(0xFF001A1B)
val primaryContainerDarkMediumContrast = Color(0xFF479DA2)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFB5D0D1)
val onSecondaryDarkMediumContrast = Color(0xFF001A1B)
val secondaryContainerDarkMediumContrast = Color(0xFF7B9697)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFBACBEE)
val onTertiaryDarkMediumContrast = Color(0xFF031630)
val tertiaryContainerDarkMediumContrast = Color(0xFF8091B1)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0E1415)
val onBackgroundDarkMediumContrast = Color(0xFFDDE4E4)
val surfaceDarkMediumContrast = Color(0xFF0E1415)
val onSurfaceDarkMediumContrast = Color(0xFFF6FCFC)
val surfaceVariantDarkMediumContrast = Color(0xFF3F4949)
val onSurfaceVariantDarkMediumContrast = Color(0xFFC3CDCD)
val outlineDarkMediumContrast = Color(0xFF9BA5A5)
val outlineVariantDarkMediumContrast = Color(0xFF7B8585)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDDE4E4)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF252B2B)
val inversePrimaryDarkMediumContrast = Color(0xFF005054)
val surfaceDimDarkMediumContrast = Color(0xFF0E1415)
val surfaceBrightDarkMediumContrast = Color(0xFF414747)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF090F10)
val surfaceContainerLowDarkMediumContrast = Color(0xFF161D1D)
val surfaceContainerDarkMediumContrast = Color(0xFF1A2121)
val surfaceContainerHighDarkMediumContrast = Color(0xFF252B2B)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF303636)

val primaryDarkHighContrast = Color(0xFFECFEFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFF84D8DD)
val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
val secondaryDarkHighContrast = Color(0xFFECFEFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFB5D0D1)
val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
val tertiaryDarkHighContrast = Color(0xFFFBFAFF)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFBACBEE)
val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
val errorDarkHighContrast = Color(0xFFFFF9F9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
val onErrorContainerDarkHighContrast = Color(0xFF000000)
val backgroundDarkHighContrast = Color(0xFF0E1415)
val onBackgroundDarkHighContrast = Color(0xFFDDE4E4)
val surfaceDarkHighContrast = Color(0xFF0E1415)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF3F4949)
val onSurfaceVariantDarkHighContrast = Color(0xFFF3FDFD)
val outlineDarkHighContrast = Color(0xFFC3CDCD)
val outlineVariantDarkHighContrast = Color(0xFFC3CDCD)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFDDE4E4)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF003032)
val surfaceDimDarkHighContrast = Color(0xFF0E1415)
val surfaceBrightDarkHighContrast = Color(0xFF343A3B)
val surfaceContainerLowestDarkHighContrast = Color(0xFF090F10)
val surfaceContainerLowDarkHighContrast = Color(0xFF161D1D)
val surfaceContainerDarkHighContrast = Color(0xFF1A2121)
val surfaceContainerHighDarkHighContrast = Color(0xFF252B2B)
val surfaceContainerHighestDarkHighContrast = Color(0xFF303636)